version: 2
registries:
  python-index-pypi-org-simple:
    type: python-index
    url: https://pypi.org/simple
    username: "${{secrets.PYTHON_INDEX_PYPI_ORG_SIMPLE_USERNAME}}"
    password: "${{secrets.PYTHON_INDEX_PYPI_ORG_SIMPLE_PASSWORD}}"

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: pingparsing
    versions:
    - 1.1.0
    - 1.2.0
    - 1.3.0
  registries:
  - python-index-pypi-org-simple
